const projects = [
  // Residential Projects
  {
    id: 'karen-marigold',
    category: 'Residential',
    categorySlug: 'residential',
    title: 'Karen Marigold Residential Home',
    location: 'Karen, Nairobi',
    client: 'Private Residence',
    scope: 'Landscape Design',
    overview: `This luxury residential home in Karen, Nairobi, required a sophisticated yet low-maintenance landscape design tailored to a premium lifestyle. Our team created a custom garden layout combining drought-resistant native plants, elegant stone walkways, and strategically placed solar garden lighting. The result is a private, eco-friendly landscape that enhances curb appeal and reduces long-term maintenance costs.`,
    images: [
      '/images/projects/karen-marigold/1.jpg',
      '/images/projects/karen-marigold/2.jpg',
      '/images/projects/karen-marigold/3.jpg',
      '/images/projects/karen-marigold/4.jpg',
      '/images/projects/karen-marigold/5.jpg',
    ],
  },
  {
    id: 'family-backyard-pool',
    category: 'Residential',
    categorySlug: 'residential',
    title: 'Family-Friendly Backyard Design with Pool & Play Area',
    location: 'Karen C, Nairobi',
    client: 'Private Residence',
    scope: 'Landscape Design',
    overview: `This backyard landscape is designed for family enjoyment, blending relaxation, play, and nature. It features a compact in-ground pool, a pergola dining space, and a child-friendly playset. Stepping stones, tropical palms, and flowering borders create a safe, vibrant outdoor living space.`,
    images: [
      '/images/projects/family-backyard-pool/1.jpg',
      '/images/projects/family-backyard-pool/2.jpg',
      '/images/projects/family-backyard-pool/3.jpg',
      '/images/projects/family-backyard-pool/4.jpg',
      '/images/projects/family-backyard-pool/5.jpg',
    ],
  },
  {
    id: 'luxury-poolside-garden',
    category: 'Residential',
    categorySlug: 'residential',
    title: 'Luxury Poolside Garden Design',
    location: 'Joska, Nairobi',
    client: 'Private Residence',
    scope: 'Landscape Design',
    overview: `This modern residential landscape blends tropical elegance with functional outdoor living. A sleek freeform pool, palm-lined lounge, and cabana create a resort-like feel for relaxation and entertainment. Drought-tolerant plants ensure low maintenance and year-round appeal.`,
    images: [
      '/images/projects/luxury-poolside-garden/1.jpg',
      '/images/projects/luxury-poolside-garden/2.jpg',
      '/images/projects/luxury-poolside-garden/3.jpg',
      '/images/projects/luxury-poolside-garden/4.jpg',
      '/images/projects/luxury-poolside-garden/5.jpg',
    ],
  },
  {
    id: 'luxury-garden-koi-pond',
    category: 'Residential',
    categorySlug: 'residential',
    title: 'Luxury Garden with Pool & Koi Pond',
    location: 'Malindi',
    client: 'Private',
    scope: 'Landscape Design',
    overview: `This project transformed a private home into a modern, resort-style sanctuary. A contemporary pool connects to a koi pond with stepping stones, surrounded by pergola lounge, play area, and lush tropical gardens. The design balances outdoor entertainment, family spaces, and tranquil garden elements.`,
    images: [
      '/images/projects/luxury-garden-koi-pond/1.jpg',
      '/images/projects/luxury-garden-koi-pond/2.jpg',
      '/images/projects/luxury-garden-koi-pond/3.jpg',
      '/images/projects/luxury-garden-koi-pond/4.jpg',
      '/images/projects/luxury-garden-koi-pond/5.jpg',
    ],
  },

  // Landscape Design Projects
  {
    id: 'urban-public-park',
    category: 'Landscape Design',
    categorySlug: 'landscape-design',
    title: 'Urban Public Park',
    location: 'Thika, Kiambu',
    client: 'County government',
    scope: 'Landscape Design',
    overview: `This urban park blends landscape architecture with civic infrastructure to create a multifunctional green space. Key features include an elevated walkway, water fountain plaza, amphitheater lawn, and interactive art installations. The design emphasizes sustainability, accessibility, and civic interaction.`,
    images: [
      '/images/projects/urban-public-park/1.jpg',
      '/images/projects/urban-public-park/2.jpg',
      '/images/projects/urban-public-park/3.jpg',
      '/images/projects/urban-public-park/4.jpg',
      '/images/projects/urban-public-park/5.jpg',
    ],
  },
  {
    id: 'outdoor-gym-garden',
    category: 'Landscape Design',
    categorySlug: 'landscape-design',
    title: 'Outdoor Gym Garden',
    location: 'Thome Garden Estate',
    client: 'Confidential',
    scope: 'Landscape Design',
    overview: `The Outdoor Gym Garden is a wellness space blending fitness, relaxation, and nature. It features five gym zones, a yoga and meditation area, winding pathways, water features, and amenities for comfort and accessibility. The design encourages holistic outdoor experiences for physical and mental well-being.`,
    images: [
      '/images/projects/outdoor-gym-garden/1.jpg',
      '/images/projects/outdoor-gym-garden/2.jpg',
      '/images/projects/outdoor-gym-garden/3.jpg',
      '/images/projects/outdoor-gym-garden/4.jpg',
      '/images/projects/outdoor-gym-garden/5.jpg',
    ],
  },
  {
    id: 'formal-garden-naivasha',
    category: 'Landscape Design',
    categorySlug: 'landscape-design',
    title: 'Formal Garden and Water Feature Landscape Design',
    location: 'Naivasha',
    client: 'Private residence',
    scope: 'Landscape Design',
    overview: `This formal garden emphasizes symmetry, elegance, and serene functionality. A reflecting pool with fountains is framed by paving patterns, manicured lawns, and flowering shrubs. The design creates a luxurious, peaceful environment for high-end residences or institutions.`,
    images: [
      '/images/projects/formal-garden-naivasha/1.jpg',
      '/images/projects/formal-garden-naivasha/2.jpg',
      '/images/projects/formal-garden-naivasha/3.jpg',
      '/images/projects/formal-garden-naivasha/4.jpg',
      '/images/projects/formal-garden-naivasha/5.jpg',
    ],
  },

  // Landscape Installation Projects
  {
    id: 'grading-lawn-runda',
    category: 'Landscape Installation',
    categorySlug: 'landscape-installation',
    title: 'Grading and Lawn Installation',
    location: 'Runda Mimosa',
    client: 'Private',
    scope: 'Landscape Installation',
    overview: `This project transformed a residential compound through professional grading and lawn establishment. Land grading improved drainage, and soil conditioning supported lush grass growth. The result is a level, fully vegetated yard that enhances usability and curb appeal.`,
    images: [
      '/images/projects/grading-lawn-runda/1.jpg',
      '/images/projects/grading-lawn-runda/2.jpg',
      '/images/projects/grading-lawn-runda/3.jpg',
      '/images/projects/grading-lawn-runda/4.jpg',
      '/images/projects/grading-lawn-runda/5.jpg',
    ],
  },

  // Hospitality and Recreational Landscape Projects
  {
    id: 'premier-resort-kisii',
    category: 'Hospitality and Recreational Landscape',
    categorySlug: 'hospitality-recreational',
    title: 'Premier Resort',
    location: 'Kisii',
    client: 'Premier Resort',
    scope: 'Landscape Design',
    overview: `This project creates a refined outdoor space combining natural beauty with comfort. Elevated cabanas, a linear pathway, manicured hedges, and tropical plants enhance the resort ambiance. A stone feature wall with a fireplace and modern lighting promotes outdoor living and privacy.`,
    images: [
      '/images/projects/premier-resort-kisii/1.jpg',
      '/images/projects/premier-resort-kisii/2.jpg',
      '/images/projects/premier-resort-kisii/3.jpg',
      '/images/projects/premier-resort-kisii/4.jpg',
      '/images/projects/premier-resort-kisii/5.jpg',
    ],
  },

  // Landscape Maintenance Projects
  {
    id: 'residential-street-juja',
    category: 'Landscape Maintenance',
    categorySlug: 'landscape-maintenance',
    title: 'Residential Street Landscaping',
    location: 'Juja Farm',
    client: 'Private Residential Estate',
    scope: 'Landscape Maintenance',
    overview: `This project features a well-maintained residential street with structured, ornamental landscaping. Trimmed hedges, topiary shrubs, and tropical plants line the driveway, while paved roads and drainage support stormwater management. The design creates a clean, organized, and tranquil suburban setting.`,
    images: [
      '/images/projects/residential-street-juja/1.jpg',
      '/images/projects/residential-street-juja/2.jpg',
      '/images/projects/residential-street-juja/3.jpg',
      '/images/projects/residential-street-juja/4.jpg',
      '/images/projects/residential-street-juja/5.jpg',
    ],
  },

  // Institutional Projects
  {
    id: 'chebirbelek-school',
    category: 'Institutional',
    categorySlug: 'institutional',
    title: 'Chebirbelek School Masterplanning',
    location: 'Bomet',
    client: 'Confidential',
    scope: 'Master Plan',
    overview: `The master plan for Chebirbelek Secondary School outlines a strategic framework for a modern, well-equipped learning environment. It integrates new classrooms, labs, library, boarding, staff quarters, and recreational amenities. The plan balances academics, welfare, and community life for a future-ready institution.`,
    images: [
      '/images/projects/chebirbelek-school/1.jpg',
      '/images/projects/chebirbelek-school/2.jpg',
      '/images/projects/chebirbelek-school/3.jpg',
      '/images/projects/chebirbelek-school/4.jpg',
      '/images/projects/chebirbelek-school/5.jpg',
    ],
  },

  // Water Feature and Pools Projects
  {
    id: 'luxury-poolside-garden',
    category: 'Water Feature and Pools',
    categorySlug: 'water-feature-pools',
    title: 'Luxury Poolside Garden Design',
    location: 'Joska, Nairobi',
    client: 'Private Residence',
    scope: 'Landscape Design',
    overview: `This landscape design features a stunning freeform pool as the centerpiece, blending tropical elegance with modern outdoor living. Lush palms, flowering shrubs, and stone-paved lounges create a resort-style atmosphere. The layout connects all zones around the pool for a seamless outdoor experience.`,
    images: [
      '/images/projects/luxury-poolside-garden/1.jpg',
      '/images/projects/luxury-poolside-garden/2.jpg',
      '/images/projects/luxury-poolside-garden/3.jpg',
      '/images/projects/luxury-poolside-garden/4.jpg',
      '/images/projects/luxury-poolside-garden/5.jpg',
    ],
  },
  {
    id: 'luxury-garden-koi-pond',
    category: 'Water Feature and Pools',
    categorySlug: 'water-feature-pools',
    title: 'Luxury Garden with Pool & Koi Pond',
    location: 'Malindi',
    client: 'Private Developer',
    scope: 'Landscape Design',
    overview: `This project features a modern pool seamlessly integrated with a tranquil koi pond, blending luxury with natural beauty. A stepping stone walkway crosses the pond, connecting garden zones. Ambient lighting and water filtration ensure a serene, resort-style outdoor space.`,
    images: [
      '/images/projects/luxury-garden-koi-pond/1.jpg',
      '/images/projects/luxury-garden-koi-pond/2.jpg',
      '/images/projects/luxury-garden-koi-pond/3.jpg',
      '/images/projects/luxury-garden-koi-pond/4.jpg',
      '/images/projects/luxury-garden-koi-pond/5.jpg',
    ],
  },

  // Irrigation Installation Projects
  {
    id: 'irrigation-kerarapon',
    category: 'Irrigation Installation',
    categorySlug: 'irrigation-installation',
    title: 'Kerarapon Residential Home',
    location: 'Kerarapon Drive',
    client: 'Private',
    scope: 'Automated Irrigation Installation',
    overview: `We implemented a fully zoned, automated sprinkler irrigation system for this premium residence in Nairobi. Rain Bird pop-up sprinklers cover lawns, borders, and shrubs with precision. The system conserves water, supports plant health, and ensures hassle-free lawn care.`,
    images: [
      '/images/projects/irrigation-kerarapon/1.jpg',
      '/images/projects/irrigation-kerarapon/2.jpg',
      '/images/projects/irrigation-kerarapon/3.jpg',
      '/images/projects/irrigation-kerarapon/4.jpg',
      '/images/projects/irrigation-kerarapon/5.jpg',
    ],
  },
];

export default projects;