const allProducts = [
    // Flowers
    {
        id: 'flower-1',
        name: 'Orchids',
        price: 'KSh 1,800',
        image: '/images/products/orchids.jpg',
        categorySlug: 'flowers',
    },
    {
        id: 'flower-2',
        name: 'Tulips',
        price: 'KSh 1,200',
        image: '/images/products/tulips.jpg',
        categorySlug: 'flowers',
    },
    {
        id: 'flower-3',
        name: 'Hydrangeas',
        price: 'KSh 1,500',
        image: '/images/products/hydrangeas.jpg',
        categorySlug: 'flowers',
    },
    {
        id: 'flower-4',
        name: 'Birds of Paradise',
        price: 'KSh 2,000',
        image: '/images/products/birds-of-paradise.jpg',
        categorySlug: 'flowers',
    },
    {
        id: 'flower-5',
        name: 'Anthurium',
        price: 'KSh 1,300',
        image: '/images/products/anthurium.jpg',
        categorySlug: 'flowers',
    },

    // Trees
    {
        id: 'tree-1',
        name: 'Bonsai',
        price: 'KSh 2,200',
        image: '/images/products/bonsai.jpg',
        categorySlug: 'trees',
    },
    {
        id: 'tree-2',
        name: 'Japanese Maple',
        price: 'KSh 3,500',
        image: '/images/products/japanese-maple.jpg',
        categorySlug: 'trees',
    },
    {
        id: 'tree-3',
        name: 'Flamboyant Tree',
        price: 'KSh 3,000',
        image: '/images/products/flamboyant.jpg',
        categorySlug: 'trees',
    },
    {
        id: 'tree-4',
        name: 'Norfolk Island Pine',
        price: 'KSh 3,800',
        image: '/images/products/norfolk-pine.jpg',
        categorySlug: 'trees',
    },
    {
        id: 'tree-5',
        name: 'Olive Tree',
        price: 'KSh 3,300',
        image: '/images/products/olive.jpg',
        categorySlug: 'trees',
    },

    // Grass
    {
        id: 'grass-1',
        name: 'Bermuda Grass',
        price: 'KSh 900',
        image: '/images/products/bermuda.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-2',
        name: 'Kikuyu Grass',
        price: 'KSh 1,000',
        image: '/images/products/kikuyu.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-3',
        name: 'Paspalum Grass',
        price: 'KSh 950',
        image: '/images/products/paspalum.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-4',
        name: 'Arabic Grass Rolls',
        price: 'KSh 1,100',
        image: '/images/products/arabic-rolls.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-5',
        name: 'Arabic Grass Bags',
        price: 'KSh 1,200',
        image: '/images/products/arabic-bags.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-6',
        name: 'Pemba Grass',
        price: 'KSh 950',
        image: '/images/products/pemba.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-7',
        name: 'Tiffsport Grass Rolls',
        price: 'KSh 1,300',
        image: '/images/products/tiffsport.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-8',
        name: 'Buffalo Grass Bags',
        price: 'KSh 1,400',
        image: '/images/products/buffalo.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-9',
        name: 'Zimbabwe Grass',
        price: 'KSh 1,100',
        image: '/images/products/zimbabwe.jpg',
        categorySlug: 'grass',
    },
    {
        id: 'grass-10',
        name: 'Artificial Grass',
        price: 'KSh 1,500',
        image: '/images/products/artificial.jpg',
        categorySlug: 'grass',
    },


    // Herbs
    {
        id: 'herb-1',
        name: 'Basil Plant',
        price: 'KSh 300',
        image: '/images/products/basil-plant.jpg',
        categorySlug: 'herbs',
    },
    {
        id: 'herb-2',
        name: 'Mint Plant',
        price: 'KSh 350',
        image: '/images/products/mint-plant.jpg',
        categorySlug: 'herbs',
    },
    {
        id: 'herb-3',
        name: 'Rosemary',
        price: 'KSh 450',
        image: '/images/products/rosemary-herb.jpg',
        categorySlug: 'herbs',
    },
    {
        id: 'herb-4',
        name: 'Thyme',
        price: 'KSh 400',
        image: '/images/products/thyme-herb.jpg',
        categorySlug: 'herbs',
    },
    {
        id: 'herb-5',
        name: 'Parsley',
        price: 'KSh 380',
        image: '/images/products/parsley-herb.jpg',
        categorySlug: 'herbs',
    },

    // Succulents
    {
        id: 'succulent-1',
        name: 'Aloe Vera Pot',
        price: 'KSh 750',
        image: '/images/products/aloe-vera.jpg',
        categorySlug: 'succulents',
    },
    {
        id: 'succulent-2',
        name: 'Echeveria Set',
        price: 'KSh 950',
        image: '/images/products/echeveria.jpg',
        categorySlug: 'succulents',
    },
    {
        id: 'succulent-3',
        name: 'Jade Plant',
        price: 'KSh 680',
        image: '/images/products/jade.jpg',
        categorySlug: 'succulents',
    },
    {
        id: 'succulent-4',
        name: 'Haworthia Pot',
        price: 'KSh 600',
        image: '/images/products/haworthia.jpg',
        categorySlug: 'succulents',
    },
    {
        id: 'succulent-5',
        name: 'Cactus Mini Pack',
        price: 'KSh 850',
        image: '/images/products/cactus-pack.jpg',
        categorySlug: 'succulents',
    },

    // Pebbles & Gravel
    {
        id: 'pebble-1',
        name: 'River Pebbles',
        price: 'KSh 1,500',
        image: '/images/products/pebbles-river.jpg',
        categorySlug: 'pebbles-gravel',
    },
    {
        id: 'pebble-2',
        name: 'White Marble Chips',
        price: 'KSh 1,800',
        image: '/images/products/pebbles-marble.jpg',
        categorySlug: 'pebbles-gravel',
    },
    {
        id: 'pebble-3',
        name: 'Crushed Granite',
        price: 'KSh 1,200',
        image: '/images/products/pebbles-granite.jpg',
        categorySlug: 'pebbles-gravel',
    },
    {
        id: 'pebble-4',
        name: 'Lava Rock Pebbles',
        price: 'KSh 1,700',
        image: '/images/products/pebbles-lava.jpg',
        categorySlug: 'pebbles-gravel',
    },
    {
        id: 'pebble-5',
        name: 'Mixed Decorative Gravel',
        price: 'KSh 1,400',
        image: '/images/products/pebbles-mixed.jpg',
        categorySlug: 'pebbles-gravel',
    },

    // Retaining Walls
    {
        id: 'wall-1',
        name: 'Concrete Retaining Blocks',
        price: 'KSh 3,000',
        image: '/images/products/wall-concrete.jpg',
        categorySlug: 'retaining-walls',
    },
    {
        id: 'wall-2',
        name: 'Natural Stone Slabs',
        price: 'KSh 4,500',
        image: '/images/products/wall-stone.jpg',
        categorySlug: 'retaining-walls',
    },
    {
        id: 'wall-3',
        name: 'Interlocking Wall Bricks',
        price: 'KSh 2,800',
        image: '/images/products/wall-interlock.jpg',
        categorySlug: 'retaining-walls',
    },
    {
        id: 'wall-4',
        name: 'Gabion Wall Cages',
        price: 'KSh 3,200',
        image: '/images/products/wall-gabion.jpg',
        categorySlug: 'retaining-walls',
    },
    {
        id: 'wall-5',
        name: 'Wooden Timber Planks',
        price: 'KSh 2,000',
        image: '/images/products/wall-timber.jpg',
        categorySlug: 'retaining-walls',
    },
    // Stones & Pavers
    {
        id: 'stones-1',
        name: 'Granite Cobblestone',
        price: 'KSh 1,200',
        image: '/images/products/granite-cobblestone.jpg',
        categorySlug: 'stones-pavers',
    },
    {
        id: 'stones-2',
        name: 'Interlocking Concrete Pavers',
        price: 'KSh 950',
        image: '/images/products/concrete-pavers.jpg',
        categorySlug: 'stones-pavers',
    },
    {
        id: 'stones-3',
        name: 'Natural Slate Pavers',
        price: 'KSh 1,400',
        image: '/images/products/slate-pavers.jpg',
        categorySlug: 'stones-pavers',
    },
    {
        id: 'stones-4',
        name: 'River Rock Stones (20kg)',
        price: 'KSh 800',
        image: '/images/products/river-rock.jpg',
        categorySlug: 'stones-pavers',
    },
    {
        id: 'stones-5',
        name: 'Flagstone Stepping Stones',
        price: 'KSh 1,600',
        image: '/images/products/flagstone-stepping.jpg',
        categorySlug: 'stones-pavers',
    },

    // Garden Tools
    {
        id: 'tool-1',
        name: 'Stainless Steel Trowel',
        price: 'KSh 550',
        image: '/images/products/tool-trowel.jpg',
        categorySlug: 'garden-tools',
    },
    {
        id: 'tool-2',
        name: 'Pruning Shears',
        price: 'KSh 900',
        image: '/images/products/tool-pruner.jpg',
        categorySlug: 'garden-tools',
    },
    {
        id: 'tool-3',
        name: 'Garden Fork',
        price: 'KSh 1,200',
        image: '/images/products/tool-fork.jpg',
        categorySlug: 'garden-tools',
    },
    {
        id: 'tool-4',
        name: 'Hand Rake',
        price: 'KSh 800',
        image: '/images/products/tool-handrake.jpg',
        categorySlug: 'garden-tools',
    },
    {
        id: 'tool-5',
        name: 'Watering Can (10L)',
        price: 'KSh 1,500',
        image: '/images/products/tool-wateringcan.jpg',
        categorySlug: 'garden-tools',
    },

    // Irrigation Equipment
    {
        id: 'irrigation-1',
        name: 'Garden Hose (15m)',
        price: 'KSh 2,000',
        image: '/images/products/irrigation-hose.jpg',
        categorySlug: 'irrigation-tools',
    },
    {
        id: 'irrigation-2',
        name: 'Drip Irrigation Kit',
        price: 'KSh 3,800',
        image: '/images/products/irrigation-drip.jpg',
        categorySlug: 'irrigation-tools',
    },
    {
        id: 'irrigation-3',
        name: 'Sprinkler Head',
        price: 'KSh 950',
        image: '/images/products/irrigation-sprinkler.jpg',
        categorySlug: 'irrigation-tools',
    },
    {
        id: 'irrigation-4',
        name: 'Tap Timer',
        price: 'KSh 2,400',
        image: '/images/products/irrigation-timer.jpg',
        categorySlug: 'irrigation-tools',
    },
    {
        id: 'irrigation-5',
        name: 'Soaker Hose',
        price: 'KSh 1,900',
        image: '/images/products/irrigation-soaker.jpg',
        categorySlug: 'irrigation-tools',
    },

    // Power Tools
    {
        id: 'power-1',
        name: 'Electric Hedge Trimmer',
        price: 'KSh 5,500',
        image: '/images/products/power-hedgetrimmer.jpg',
        categorySlug: 'power-tools',
    },
    {
        id: 'power-2',
        name: 'Cordless Leaf Blower',
        price: 'KSh 6,800',
        image: '/images/products/power-leafblower.jpg',
        categorySlug: 'power-tools',
    },
    {
        id: 'power-3',
        name: 'Corded Electric Cultivator',
        price: 'KSh 11,500',
        image: '/images/products/power-cultivator.jpg',
        categorySlug: 'power-tools',
    },
    {
        id: 'power-4',
        name: 'Chainsaw (Electric)',
        price: 'KSh 10,500',
        image: '/images/products/power-chainsaw.jpg',
        categorySlug: 'power-tools',
    },
    {
        id: 'power-5',
        name: 'Garden Shredder',
        price: 'KSh 8,900',
        image: '/images/products/power-shredder.jpg',
        categorySlug: 'power-tools',
    },
    // Planters & Pots
    {
        id: 'planter-1',
        name: 'Fibreglass Pot',
        price: 'KSh 1,200',
        image: '/images/products/fibreglass-pot.jpg',
        categorySlug: 'planters-pots',
    },
    {
        id: 'planter-2',
        name: 'Concrete Planter',
        price: 'KSh 1,100',
        image: '/images/products/concrete-planter.jpg',
        categorySlug: 'planters-pots',
    },
    {
        id: 'planter-3',
        name: 'Galvanized Steel Pot',
        price: 'KSh 1,400',
        image: '/images/products/galvanized-steel-pot.jpg',
        categorySlug: 'planters-pots',
    },
    {
        id: 'planter-4',
        name: 'Stainless Steel Pot',
        price: 'KSh 1,600',
        image: '/images/products/stainless-steel-pot.jpg',
        categorySlug: 'planters-pots',
    },
    {
        id: 'planter-5',
        name: 'Plastic Pot',
        price: 'KSh 700',
        image: '/images/products/plastic-pot.jpg',
        categorySlug: 'planters-pots',
    },
    {
        id: 'planter-6',
        name: 'Terracotta Pot',
        price: 'KSh 850',
        image: '/images/products/terracotta-pot.jpg',
        categorySlug: 'planters-pots',
    },

    // Hanging Planters
    {
        id: 'hanging-1',
        name: 'Macrame Hanging Basket',
        price: 'KSh 1,200',
        image: '/images/products/macrame-hanging.jpg',
        categorySlug: 'hanging-planters',
    },
    {
        id: 'hanging-2',
        name: 'Metal Hanging Pot',
        price: 'KSh 950',
        image: '/images/products/metal-hanging-pot.jpg',
        categorySlug: 'hanging-planters',
    },
    {
        id: 'hanging-3',
        name: 'Coconut Coir Hanging Basket',
        price: 'KSh 800',
        image: '/images/products/coir-hanging.jpg',
        categorySlug: 'hanging-planters',
    },
    {
        id: 'hanging-4',
        name: 'Self-Watering Hanging Planter',
        price: 'KSh 1,400',
        image: '/images/products/self-watering-hanging.jpg',
        categorySlug: 'hanging-planters',
    },
    {
        id: 'hanging-5',
        name: 'Double Tier Hanging Pots',
        price: 'KSh 1,600',
        image: '/images/products/double-tier-hanging.jpg',
        categorySlug: 'hanging-planters',
    },

    // Garden Decor
    {
        id: 'decor-1',
        name: 'Garden Gnome',
        price: 'KSh 1,300',
        image: '/images/products/garden-gnome.jpg',
        categorySlug: 'garden-decor',
    },
    {
        id: 'decor-2',
        name: 'Wind Chimes',
        price: 'KSh 700',
        image: '/images/products/wind-chimes.jpg',
        categorySlug: 'garden-decor',
    },
    {
        id: 'decor-3',
        name: 'Stone Garden Owl',
        price: 'KSh 950',
        image: '/images/products/garden-owl.jpg',
        categorySlug: 'garden-decor',
    },
    {
        id: 'decor-4',
        name: 'Butterfly Stakes Set',
        price: 'KSh 600',
        image: '/images/products/butterfly-stakes.jpg',
        categorySlug: 'garden-decor',
    },
    {
        id: 'decor-5',
        name: 'Solar Garden Ball',
        price: 'KSh 1,200',
        image: '/images/products/solar-ball.jpg',
        categorySlug: 'garden-decor',
    },

    // Mulch & Soil
    {
        id: 'soil-1',
        name: 'Organic Potting Soil (10kg)',
        price: 'KSh 650',
        image: '/images/products/potting-soil.jpg',
        categorySlug: 'mulch-soil',
    },
    {
        id: 'soil-2',
        name: 'Red Bark Mulch (5kg)',
        price: 'KSh 550',
        image: '/images/products/bark-mulch.jpg',
        categorySlug: 'mulch-soil',
    },
    {
        id: 'soil-3',
        name: 'Coco Peat Block',
        price: 'KSh 400',
        image: '/images/products/coco-peat.jpg',
        categorySlug: 'mulch-soil',
    },
    {
        id: 'soil-4',
        name: 'Vermicompost (5kg)',
        price: 'KSh 750',
        image: '/images/products/vermicompost.jpg',
        categorySlug: 'mulch-soil',
    },
    {
        id: 'soil-5',
        name: 'Topsoil Sack (20kg)',
        price: 'KSh 950',
        image: '/images/products/topsoil.jpg',
        categorySlug: 'mulch-soil',
    },

    // Fertilizers
    {
        id: 'fertilizer-1',
        name: 'Compost Fertilizer (5kg)',
        price: 'KSh 900',
        image: '/images/products/compost.jpg',
        categorySlug: 'fertilizers',
    },
    {
        id: 'fertilizer-2',
        name: 'NPK Granules',
        price: 'KSh 1,100',
        image: '/images/products/npk.jpg',
        categorySlug: 'fertilizers',
    },
    {
        id: 'fertilizer-3',
        name: 'Bone Meal Powder',
        price: 'KSh 850',
        image: '/images/products/bone-meal.jpg',
        categorySlug: 'fertilizers',
    },
    {
        id: 'fertilizer-4',
        name: 'Liquid Seaweed Fertilizer',
        price: 'KSh 1,300',
        image: '/images/products/seaweed.jpg',
        categorySlug: 'fertilizers',
    },
    {
        id: 'fertilizer-5',
        name: 'Organic Pellets',
        price: 'KSh 950',
        image: '/images/products/organic-pellets.jpg',
        categorySlug: 'fertilizers',
    },

    // Outdoor Furniture
    {
        id: 'furniture-1',
        name: 'Rattan Patio Chair',
        price: 'KSh 5,500',
        image: '/images/products/rattan-chair.jpg',
        categorySlug: 'outdoor-furniture',
    },
    {
        id: 'furniture-2',
        name: 'Teak Garden Bench',
        price: 'KSh 8,200',
        image: '/images/products/teak-bench.jpg',
        categorySlug: 'outdoor-furniture',
    },
    {
        id: 'furniture-3',
        name: 'Outdoor Bistro Set',
        price: 'KSh 7,000',
        image: '/images/products/bistro-set.jpg',
        categorySlug: 'outdoor-furniture',
    },
    {
        id: 'furniture-4',
        name: 'Foldable Garden Table',
        price: 'KSh 3,800',
        image: '/images/products/foldable-table.jpg',
        categorySlug: 'outdoor-furniture',
    },
    {
        id: 'furniture-5',
        name: 'Wicker Lounge Chair',
        price: 'KSh 6,700',
        image: '/images/products/wicker-chair.jpg',
        categorySlug: 'outdoor-furniture',
    },
    {
        id: 'furniture-6',
        name: 'Rattan Garden Sofa',
        price: 'KSh 15,000',
        image: '/images/products/furniture-rattan-sofa.jpg',
        categorySlug: 'outdoor-furniture',
    },
    {
        id: 'furniture-7',
        name: 'Foldable Wooden Bench',
        price: 'KSh 6,800',
        image: '/images/products/furniture-wooden-bench.jpg',
        categorySlug: 'outdoor-furniture',
    },

    // Garden Lighting
    {
        id: 'lighting-1',
        name: 'Solar Path Lights (4 Pack)',
        price: 'KSh 2,000',
        image: '/images/products/solar-path.jpg',
        categorySlug: 'garden-lighting'
    },
    {
        id: 'lighting-4',
        name: 'Motion Sensor Light',
        price: 'KSh 1,900',
        image: '/images/products/motion-light.jpg',
        categorySlug: 'garden-lighting',
    },
    {
        id: 'lighting-5',
        name: 'Color Changing Solar Globe',
        price: 'KSh 2,200',
        image: '/images/products/solar-globe.jpg',
        categorySlug: 'garden-lighting',
    },
    {
        id: 'lighting-6',
        name: 'Solar Garden Lights (Pack of 6)',
        price: 'KSh 3,200',
        image: '/images/products/lighting-solar-pack.jpg',
        categorySlug: 'garden-lighting',
    },
    {
        id: 'lighting-7',
        name: 'LED Pathway Lights',
        price: 'KSh 2,700',
        image: '/images/products/lighting-pathway.jpg',
        categorySlug: 'garden-lighting',
    },

    // Water Features
    {
        id: 'water-1',
        name: 'Ceramic Bird Bath',
        price: 'KSh 3,500',
        image: '/images/products/bird-bath.jpg',
        categorySlug: 'water-features',
    },
    {
        id: 'water-2',
        name: 'Mini Fountain Kit',
        price: 'KSh 4,800',
        image: '/images/products/mini-fountain.jpg',
        categorySlug: 'water-features',
    },
    {
        id: 'water-3',
        name: 'Waterfall Rock Feature',
        price: 'KSh 6,200',
        image: '/images/products/rock-waterfall.jpg',
        categorySlug: 'water-features',
    },
    {
        id: 'water-4',
        name: 'Solar Pond Pump',
        price: 'KSh 3,000',
        image: '/images/products/pond-pump.jpg',
        categorySlug: 'water-features',
    },
    {
        id: 'water-5',
        name: 'LED Water Fountain Bowl',
        price: 'KSh 5,400',
        image: '/images/products/fountain-bowl.jpg',
        categorySlug: 'water-features',
    },
    {
        id: 'water-6',
        name: 'Ceramic Fountain Bowl',
        price: 'KSh 8,500',
        image: '/images/products/water-ceramic-fountain.jpg',
        categorySlug: 'water-features',
    },
    {
        id: 'water-7',
        name: 'Rock Cascade Fountain',
        price: 'KSh 12,400',
        image: '/images/products/water-rock-cascade.jpg',
        categorySlug: 'water-features',
    },

    // Palms
    {
        id: 'palms-1',
        name: 'Cycads',
        price: 'KSh 2,800',
        image: '/images/products/palm-cycad.jpg',
        categorySlug: 'palms',
    },
    {
        id: 'palms-2',
        name: 'Lipstick Palm',
        price: 'KSh 4,500',
        image: '/images/products/palm-lipstick.jpg',
        categorySlug: 'palms',
    },
    {
        id: 'palms-3',
        name: 'Royal Palm',
        price: 'KSh 3,700',
        image: '/images/products/palm-royal.jpg',
        categorySlug: 'palms',
    },
    {
        id: 'palms-4',
        name: 'Bismark Palm',
        price: 'KSh 3,400',
        image: '/images/products/palm-bismark.jpg',
        categorySlug: 'palms',
    },
    {
        id: 'palms-5',
        name: 'Bottle Palm',
        price: 'KSh 3,600',
        image: '/images/products/palm-bottle.jpg',
        categorySlug: 'palms',
    },
    // Lawn Mowers
    {
        id: 'mower-1',
        name: 'Honda GXV160 Petrol Mower',
        price: 'KSh 65,000',
        image: '/images/products/honda-gxv160.jpg',
        categorySlug: 'lawn-mowers',
    },
    {
        id: 'mower-2',
        name: 'Makita Electric Lawn Mower ELM3320',
        price: 'KSh 24,500',
        image: '/images/products/makita-elm3320.jpg',
        categorySlug: 'lawn-mowers',
    },
    {
        id: 'mower-3',
        name: 'Black & Decker BEMW451BH Electric Mower',
        price: 'KSh 18,000',
        image: '/images/products/black-decker-bemw451bh.jpg',
        categorySlug: 'lawn-mowers',
    },
    {
        id: 'mower-4',
        name: 'Bosch ARM 34 Electric Lawn Mower',
        price: 'KSh 28,000',
        image: '/images/products/bosch-arm34.jpg',
        categorySlug: 'lawn-mowers',
    },
    {
        id: 'mower-5',
        name: 'Hyundai HYM430SP Self-Propelled Petrol Mower',
        price: 'KSh 52,000',
        image: '/images/products/hyundai-hym430sp.jpg',
        categorySlug: 'lawn-mowers',
    },

];

export default allProducts;
