const categories = [
    {
        slug: 'flowers',
        name: 'Flowers',
        description: 'Add vibrant colors and fragrance to your garden.',
        image: '/product-category/flowers.jpeg',
    },
    {
        slug: 'palms',
        name: 'Palms',
        description: 'Exotic palms for a tropical touch.',
        image: '/product-category/palms.jpeg',
    },
    {
        slug: 'trees',
        name: 'Trees',
        description: 'Shade, privacy, and beauty for any landscape.',
        image: '/product-category/trees.jpeg',
    },
    {
        slug: 'grass',
        name: 'Grass',
        description: 'Lawn solutions for lush, green spaces.',
        image: '/product-category/grass.jpeg',
    },
    {
        slug: 'herbs',
        name: 'Herbs',
        description: 'Grow fresh herbs for cooking and wellness.',
        image: '/product-category/herbs.jpeg',
    },
    {
        slug: 'succulents',
        name: 'Succulents',
        description: 'Drought-resistant and decorative plant options.',
        image: '/product-category/succulents.jpeg',
    },
    {
        slug: 'stones-pavers',
        name: 'Stones & Pavers',
        description: 'Elegant and durable pathways and bed borders.',
        image: '/product-category/stones-pavers.jpeg',
    },
    {
        slug: 'pebbles-gravel',
        name: 'Pebbles & Gravel',
        description: 'Drainage and decorative texture for any yard.',
        image: '/product-category/pebbles-gravel.jpeg',
    },
    {
        slug: 'retaining-walls',
        name: 'Retaining Walls',
        description: 'Soil support and stylish design elements.',
        image: '/product-category/retaining-wall.jpeg',
    },
    {
        slug: 'garden-tools',
        name: 'Garden Tools',
        description: 'Reliable tools for daily gardening tasks.',
        image: '/product-category/garden-tools.jpeg',
    },
    {
        slug: 'irrigation-tools',
        name: 'Irrigation Tools',
        description: 'Irrigation solutions to keep your plants healthy.',
        image: '/product-category/irrigation-tools.jpeg',
    },
    {
        slug: 'power-tools',
        name: 'Power Tools',
        description: 'Efficient equipment for demanding outdoor jobs.',
        image: '/product-category/power-tools.jpeg',
    },
    {
        slug: 'planters-pots',
        name: 'Planters & Pots',
        description: 'Functional and decorative plant containers.',
        image: '/product-category/planters-pots.jpeg',
    },
    {
        slug: 'hanging-planters',
        name: 'Hanging Planters',
        description: 'Stylish vertical planting options.',
        image: '/product-category/hanging-planters.jpeg',
    },
    {
        slug: 'garden-decor',
        name: 'Garden Decor',
        description: 'Statues, signs, and artistic garden accents.',
        image: '/product-category/garden-decor.jpeg',
    },
    {
        slug: 'mulch-soil',
        name: 'Mulch & Soil',
        description: 'Vital nutrients for plant growth and moisture retention.',
        image: '/product-category/mulch-soil.jpeg',
    },
    {
        slug: 'fertilizers',
        name: 'Fertilizers',
        description: 'Organic and chemical options for plant nutrition.',
        image: '/product-category/fertilizers.jpeg',
    },
    {
        slug: 'outdoor-furniture',
        name: 'Outdoor Furniture',
        description: 'Relaxing seating and dining options for your garden.',
        image: '/product-category/outdoor-furniture.jpeg',
    },
    {
        slug: 'garden-lighting',
        name: 'Garden Lighting',
        description: 'Solar and electric lighting to beautify your nights.',
        image: '/product-category/garden-lighting.jpeg',
    },
    {
        slug: 'water-features',
        name: 'Water Features',
        description: 'Fountains, ponds, and water elements for serenity.',
        image: '/product-category/water-features.jpeg',
    },
    {
        slug: 'lawn-mowers',
        name: 'Lawn Mowers',
        description: 'Efficient machines for keeping your lawn perfectly trimmed.',
        image: '/product-category/lawn-mowers.jpeg',
    },
];

export default categories;
